use crate::rules::bitboard::Bitboard;
use crate::rules::luts::EngineLUTs;
use crate::rules::move_utils::{
    align_relative_mask, compute_ray_moves, generate_7bit_key, get_orthogonal_mask,
    shift_and_clip_mask,
};

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub struct Move {
    payload: u16,
}

impl Move {
    const FROM_MASK: u16 = 0x003F; // Lowest 6 bits
    const TO_MASK: u16   = 0x0FC0; // Middle 6 bits
    const FLAG_MASK: u16 = 0xF000; // Top 4 bits

    #[inline]
    pub const fn new(from: u8, to: u8, flags: u8) -> Self {
        Self {
            payload: (from as u16 & Self::FROM_MASK)
                | ((to as u16) << 6 & Self::TO_MASK)
                | ((flags as u16) << 12 & Self::FLAG_MASK),
        }
    }

    #[inline]
    pub const fn from_square(&self) -> u8 {
        (self.payload & Self::FROM_MASK) as u8
    }

    #[inline]
    pub const fn to_square(&self) -> u8 {
        ((self.payload & Self::TO_MASK) >> 6) as u8
    }

    #[inline]
    pub const fn flags(&self) -> u8 {
        ((self.payload & Self::FLAG_MASK) >> 12) as u8
    }

    #[inline]
    pub fn extract_moves_from_mask(from_idx: u8, mut destination_mask: Bitboard, flags: u8) -> Vec<Self> {
        let mut moves = Vec::with_capacity(destination_mask.count_ones() as usize);
        while !destination_mask.is_empty() {
            let to_idx = destination_mask.pop_lsb();
            moves.push(Self::new(from_idx, to_idx, flags));
        }
        moves
    }
}

// ============================================================================
// MAIN GENERATION PIPELINES
// ============================================================================

/// Evaluates and combines both orthogonal and diagonal movement sets for a single 
/// specified piece index on the board.
pub fn generate_piece_moves<const IS_CONTROL_EVAL: bool>(
    piece_idx: u8,
    allied_pieces: Bitboard,
    enemy_pieces: Bitboard,
    luts: &EngineLUTs,
) -> Bitboard {
    let ortho_moves = generate_orthogonal_moves::<IS_CONTROL_EVAL>(
        piece_idx,
        allied_pieces,
        enemy_pieces,
        luts,
    );
    
    let diag_moves = generate_diagonal_moves::<IS_CONTROL_EVAL>(
        piece_idx,
        allied_pieces,
        enemy_pieces,
        luts,
    );

    ortho_moves | diag_moves
}

// ============================================================================
// ORTHOGONAL ROTATIONAL IMPLEMENTATION
// ============================================================================

/// Scans the immediate neighborhood of a piece, identifies all valid allied pivots, 
/// and aggregates their absolute rotational results.
pub fn generate_orthogonal_moves<const IS_CONTROL_EVAL: bool>(
    piece_idx: u8,
    allied_pieces: Bitboard,
    enemy_pieces: Bitboard,
    luts: &EngineLUTs,
) -> Bitboard {
    // 1. Gather the raw orthogonal adjacency template mask for this square
    let orthogonal_mask = get_orthogonal_mask(piece_idx, luts);

    // 2. Intersect with allied pieces; your allies inherently function as the valid anchors (pivots)
    let mut pivot_bits = orthogonal_mask & allied_pieces;
    let mut destination_moves = Bitboard::EMPTY;

    // Hot-loop utilizing our high-performance destructive bit stripping
    while !pivot_bits.is_empty() {
        let pivot_idx = pivot_bits.pop_lsb();

        let pivot_moves = generate_moves_for_pivot::<IS_CONTROL_EVAL>(
            piece_idx,
            pivot_idx,
            allied_pieces,
            enemy_pieces,
            luts,
        );
        destination_moves |= pivot_moves;
    }

    // --- DEFERRED FRIENDLY FIRE FILTERING ---
    // In standard play, mask out squares containing your own pieces at the very end.
    // If evaluating control values, we keep friendly fire interactions intact.
    if IS_CONTROL_EVAL {
        destination_moves
    } else {
        destination_moves & !allied_pieces
    }
}

/// Evaluates the movement or control profile generated by a single, specific pivot 
/// relative to the active moving piece.
pub fn generate_moves_for_pivot<const IS_CONTROL_EVAL: bool>(
    piece_idx: u8,
    pivot_idx: u8,
    allied_pieces: Bitboard,
    enemy_pieces: Bitboard,
    luts: &EngineLUTs,
) -> Bitboard {
    // Merge positions into a combined grid to manage board obstacles
    let mut total_occupancy = allied_pieces | enemy_pieces;

    // --- DYNAMIC CONTROL FLUIDITY ---
    // If evaluating control/influence vectors, we ignore any allied pieces that are orthogonal 
    // to our active pivot, effectively allowing our moving piece to "slide through" them.
    if IS_CONTROL_EVAL {
        let adjacent_to_pivot = get_orthogonal_mask(pivot_idx, luts);
        total_occupancy &= !(adjacent_to_pivot & allied_pieces);
    }

    // Step 2: Extract our dense 7-bit neighborhood rotation key
    let (key, initial_offset_type) = generate_7bit_key(piece_idx, pivot_idx, total_occupancy);

    // Step 3: Fast O(1) rotation status lookup
    let relative_arrival_mask = luts.neighborhood_rotation_lut[key as usize];

    // Step 4: Re-align directional indices and translate the spatial move-mask template over the pivot
    let absolute_cardinal_mask = align_relative_mask(relative_arrival_mask, initial_offset_type);
    let local_move_mask = luts.cardinal_offset_lut[absolute_cardinal_mask as usize];
    
    // Pass raw interior value into helper for the 128-bit shift trick
    shift_and_clip_mask(local_move_mask.0, pivot_idx, luts)
}

// ============================================================================
// DIAGONAL RAYCASTING IMPLEMENTATION
// ============================================================================

/// Calculates long-range diagonal frog-hops radiating from a single starting index.
pub fn generate_diagonal_moves<const IS_CONTROL_EVAL: bool>(
    piece_idx: u8,
    allied_pieces: Bitboard,
    _enemy_pieces: Bitboard, // Unused here since enemies don't block the hop path transit
    luts: &EngineLUTs,
) -> Bitboard {
    let rays = luts.diagonal_ray_lut[piece_idx as usize];
    
    // Per your deduction: diagonal hops pass clean over empty or enemy-held squares.
    // Only your own allied pieces serve as the actual anchors you leap over.
    let blockers = allied_pieces;

    // Native compiler intrinsics for hardware bit scans
    let scan_forward = |b: Bitboard| b.trailing_zeros();
    let scan_backward = |b: Bitboard| 63 - b.leading_zeros();

    let mut valid_moves = Bitboard::EMPTY;

    // Scan all 4 diagonal vectors independently
    valid_moves |= compute_ray_moves::<IS_CONTROL_EVAL, _>(rays.ne, blockers, piece_idx, 9, scan_forward);
    valid_moves |= compute_ray_moves::<IS_CONTROL_EVAL, _>(rays.nw, blockers, piece_idx, 7, scan_forward);
    valid_moves |= compute_ray_moves::<IS_CONTROL_EVAL, _>(rays.se, blockers, piece_idx, -7, scan_backward);
    valid_moves |= compute_ray_moves::<IS_CONTROL_EVAL, _>(rays.sw, blockers, piece_idx, -9, scan_backward);

    valid_moves
}